# Generated by Django 2.2.5 on 2020-05-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('IACO', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=4)),
                ('location', models.CharField(max_length=100)),
                ('incident_country', models.CharField(max_length=100)),
                ('plane_type', models.CharField(max_length=100)),
                ('airport_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application1.Airports')),
            ],
        ),
        migrations.CreateModel(
            name='Incidents_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_type', models.CharField(max_length=5)),
                ('fatalities', models.IntegerField()),
                ('airline', models.CharField(max_length=100)),
                ('id_incidents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application1.Incidents')),
            ],
        ),
    ]
