# Generated by Django 2.2.5 on 2020-05-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports_arr',
            fields=[
                ('IACO', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Airports_dep',
            fields=[
                ('IACO', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='incidents',
            name='airport_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application1.Airports_dep'),
        ),
        migrations.DeleteModel(
            name='Airports',
        ),
        migrations.AddField(
            model_name='incidents',
            name='airport_arr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application1.Airports_arr'),
            preserve_default=False,
        ),
    ]
