# Generated by Django 2.2.5 on 2020-05-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0008_auto_20200507_1030'),
    ]

    operations = [
    ]
