# Generated by Django 2.2.5 on 2020-05-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0009_auto_20200507_1104'),
    ]

    operations = [
    ]
