# Generated by Django 2.2.5 on 2020-05-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0007_auto_20200507_1026'),
    ]

    operations = [
    ]
